### ISSUE TITLE
Setup boilarplate for go

### ISSUE THREAD

**Issue by LautaroJayat** [SuperNerdIT/telepathic#1]
## Background
We are starting a new project, so we need some kind of structure.
It does not matter if we are going to change it latter.

## Tasks

- [ ] Setup a folder structure
- [ ] Setup go modules
- [ ] Setup github actions folders
- [ ] setup vscode folder
- [ ] Write some lines in the Readme
- [ ] Add a little main function
- [ ] Add a docs folder
