### ISSUE TITLE
Plan and propose a place to discuss and design the basic event notification features

### ISSUE THREAD

**Issue by LautaroJayat** [SuperNerdIT/telepathic#2]
## Background
We want a message broker, it would be cool if it has some features (just saying).

## Tasks
- [x] Find a place to discuss these things
- [x] Find a tool to link were we can make draws and so on
- [x] Find a place to create some kind of roadmap
- [x] Put all those things in here

**Comment by pablogugarcia** [comment]
For the diagrams a folder in the repository  (like /docs) would be a good option. See https://gist.github.com/philip-gai/9c801bdff0ec4c1954f18217dc808476 (diagrams io into visual code)

For discussions we can use notion https://www.notion.so/es-es or maybe fork a open source clone https://github.com/AppFlowy-IO/AppFlowy ( written in Rust .. ) and find some server for deploy this

**Comment by LautaroJayat** [comment]
Diagrams io for vscode, I'm totally in!
I think we could use the github markdown for sequence diagrams too.
For discussion, maybe we could keep things in here. Then, if we need something more, we could move to notion.so.

**Comment by LautaroJayat** [comment]
@pablogugarcia we forgot Github already has these kind of boards and wikis and so on:


![Image](https://user-images.githubusercontent.com/48366106/182956078-2f577619-11d7-462c-bfb7-016de107a26e.png)

Lets just use the repo's wiki and the discussion board.
What do you think?

**Comment by LautaroJayat** [comment]
To summarize:

* Discussions in github discussions.
* Docs in docs folder and the wiki
* diagrams using vscode drawio extension

**Comment by LautaroJayat** [comment]
To summarize:

* Discussions in github discussions.
* Docs in docs folder and the wiki
* diagrams using vscode drawio extension
