### ISSUE TITLE
Discuss and decide which events will trigger which stage of the pipelines

### ISSUE THREAD

**Issue by LautaroJayat** [SuperNerdIT/telepathic#5]
## Background
As we want to set up CI/CD it seems to be a good idea to discuss which things will cause which jobs

## Tasks

- [ ] Enumerate events 
- [ ] Decide which of those needs to be taken into consideration before start thinking into build releases and full e2e testing
- [ ] Decide what do we want for each of these steps
- [ ] Document that in a markdown file in this same repo
